version: "2"

services:
  conjur_5:
    image: cyberark/conjur:0.3.0-stable
    command: server -a default
    environment:
      DATABASE_URL: postgres://postgres@pg/postgres
      CONJUR_DATA_KEY: 'WMfApcDBtocRWV+ZSUP3Tjr5XNU+Z2FdBb6BEezejIs='
    ports:
      - 80:80
    depends_on:
      - pg

  pg:
    image: postgres:9.3

  conjur_4:
    image: registry2.itci.conjur.net/conjur-appliance-cuke-master:4.9-stable
    security_opt:
      - seccomp:unconfined
    environment:
      CONJUR_AUTHN_LOGIN: admin
      CONJUR_AUTHN_API_KEY: secret
    volumes:
      - ./policy/:/etc/policy/:ro
    ports:
      - 8443:443

  client:
    image: conjurinc/cli5
    depends_on: [ conjur ]
    environment:
      CONJUR_APPLIANCE_URL: http://conjur
      CONJUR_ACCOUNT: default
      CONJUR_AUTHN_API_KEY:
      CONJUR_AUTHN_LOGIN: admin
    volumes:
      - ./policy:/policy
