version: "2"

services:
  conjur_5:
    image: cyberark/conjur
    command: server -a default
    environment:
      DATABASE_URL: postgres://postgres@pg/postgres
      CONJUR_DATA_KEY: 'WMfApcDBtocRWV+ZSUP3Tjr5XNU+Z2FdBb6BEezejIs='
    ports:
      - 80:80
    depends_on:
      - pg

  pg:
    image: postgres:9.4

  client:
    image: cyberark/conjur-cli:5
    depends_on: [ conjur_5 ]
    environment:
      CONJUR_APPLIANCE_URL: http://conjur_5
      CONJUR_ACCOUNT: default
      CONJUR_AUTHN_API_KEY:
      CONJUR_AUTHN_LOGIN: admin
    volumes:
      - ./policy:/policy
